#!/bin/sh

sh ~/.fehbg &
# feh --recursive --randomize --bg-fill ~/wallpapers
killall sxhkd; sxhkd &
killall picom; picom -b --experimental-backends &
killall polybar; polybar default &

#bspwm-blurwall &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width 3
bspc config window_gap 16
bspc config split_ratio 0.52
bspc config borderless_monocle true
bspc config gapless_monocle true

bspc config swallow_first_click true
#bspc config focus_follows_pointer true
#bspc config pointer_follows_focus true

# Color
#. "${HOME}/.cache/wal/colors.sh"
#bspc config normal_border_color "$color1"
#bspc config active_border_color "$color2"
#bspc config focused_border_color "$color15"
#bspc config presel_feedback_color "$color1"
##bspc config presel_border_color "$color1"

bspc config normal_border_color "#282828"
bspc config active_border_color "#ebdbb2"
bspc config focused_border_color "#fe8019"

# Window rules
bspc rule -a Zathura state=tiled
bspc rule -a Minecraft desktop='^3' state=floating follow=on
bspc rule -a CSGO state=fullscreen

#bspc subscribe node_state | while read -r _ _ _ node state status; do
    #if [[ "$state" == "floating" ]] || [[ "" ]]; then
        #case "$status" in
            #off) xprop -id "$node" -remove _COMPTON_SHADOW;;
            #on) xprop -id "$node" -f _COMPTON_SHADOW 32c -set _COMPTON_SHADOW 1;;
        #esac
    #fi
#done
